### PR TITLE
Refactor the project.

### PR DESCRIPTION
**Pull request by andy840119**
What's done in this PR:
- Upgrade the test environment to .net6
- Refactor the fucking client.

I'v notice that API is broken in the #12, but not fixed in this PR.
Not really when to fix that because busy recently.

### CODE REVIEW

**Comment by andy840119** [comment]
Seems unit test is runnable, so let it merge.

**Comment by SylveonDeko** [comment]
When package upload

**Comment by andy840119** [comment]
Not really sure.
This change does not affect any api.

**Comment by andy840119** [comment]
Guess after add the tag release in the github action.
Not really sure when, because working on more important project now.

**Comment by SylveonDeko** [comment]
What if I compile and upload the nuget package?

**Comment by andy840119** [comment]
If you are willing to maintain this project, i can transfer this project and [Nuget upload permission](https://www.nuget.org/packages/NHentaiAPI/) to you 🙆🏼‍♂️

**Comment by SylveonDeko** [comment]
Sure! More or less because I actively use it in my discord bot lol

**Comment by andy840119** [comment]
OK
Give me your nuget account 👌🏼 .

**Comment by SylveonDeko** [comment]
Sylveon76
***@***.***

**Comment by andy840119** [comment]
Transfered.

**Comment by SylveonDeko** [comment]
Thanks! Will do what I can to get this running again!
On 5/4/2022 10:35:35 PM, andy ***@***.***> wrote:
Transfered.

**Pull request merged**
